name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        browser: [chrome] # Running tests in Chrome, you can add firefox or other browsers if needed

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Set up environment variables from .env (using a secret in GitHub)
      - name: Add ENV variables
        run: |
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env

      # Step 5: Run Cypress tests in headless mode using the test-headless script
      - name: Run Cypress tests headless
        env: # Set environment variables directly
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_URL: 'https://gorest.co.in'
        run: npm run test-headless

      # Step 6: Upload Cypress test results (Mochawesome Report)
      - name: Upload Cypress Mochawesome Reports
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome

      # Step 7: Upload Cypress videos if tests fail
      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos

      # Step 8: Upload Cypress screenshots if tests fail
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots  
