name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        browser: [chrome] # Running tests in Chrome, you can add firefox or other browsers if needed

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Set up environment variables from .env (using a secret in GitHub)
      - name: Add ENV variables
        run: |
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env

      # Step 5: Run Cypress tests in headless mode using the test-headless script
      - name: Run Cypress tests headless
        run: npm run test-headless
